### PR TITLE
Adds Christine Moulen

### PR DESCRIPTION
**Pull request by orbitee**
Just added myself to the list.

### CODE REVIEW

**Review by matt-bernhardt — APPROVED** [review]
The change looks good!

I should note that this triggered a condition that needed extra resolution (a merge conflict), which we didn't cover in the overview talk. You did everything right - we'll cover how to resolve conflicts in a future talk.

**Comment by matt-bernhardt** [comment]
Now that the PR has been approved, the practice that we follow calls for the proposer to do the actual merging via the "Merge pull request" button on this page.

I don't know that we covered this specifically in the git overview, sorry.

**Comment by JPrevost** [comment]
Well... only people in our github org can merge. I don't think we should add everyone at this time. @orbitee can merge sure, but in general we need to do that for everyone else.

**Comment by orbitee** [comment]
Thanks.  I noticed the conflict, but that's one thing I never had to deal with in svn.  I knew it was a possibility, but it didn't come up.  With many authors, it probably happens more often.

Christine
________________________________

**Pull request merged**
